const obj = {
  name: "吴尚哲",
  avatar: "",
  phone: "",
  card_num: "701201852",
  address_detail: "",
  borrow_rule_id: 59,
  gender: 3,
  expire_time: "9999-01-01 00:00:00",
  birthday: "",
  deposit: "",
  identity: "",
  school: "",
  contact_name: "",
  grade: "8",
  contact_phone: "",
  class: "4",
  number: "",
  note: "",
  clent: 2,
};
